export interface ISuperAdminSettings {
settingsId?:number,
siteName:string,
siteDescription:string,
facebookLink:string,
instagramLink:string,
  logoWhite: File | null,
  logoDark: File | null,
  defaultImage: File | null,
  coverImage: File | null,
  faviconIcon: File | null,
  frontImage: File | null,
  hostEmail:string,
  hostName:string,
  hostPassword:string,
  host:string,
  port:string,
  stripeApiKey:string,
  stripeApiSecretKey:string,
  twilioAccountId:string,
  twilioAuthToken:string,
  twilioMobileNo:string,

}
